export_symlink:
  link_suffixes:
  - .mkv
  - .iso
  - .ts
  - .mp4
  - .avi
  - .rmvb
  - .wmv
  - .m2ts
  - .mpg
  - .flv
  - .rm
  meta_suffixes:
  - .nfo
  - .jpg
  - .png
  - .svg
  - .ass
  - .srt
  - .sup
  thread_count: 4
  link_folders:
  - C:/Users/wiz/Desktop/dev/Emby115Toolkit/utils
  - C:/Users/wiz/Desktop/dev/Emby115Toolkit/logs
  - C:/Users/wiz/Desktop/dev/Emby115Toolkit/tabs
  target_folder: C:/emby-as-115/MOVIE
