"""媒体条目制片国家/地区名称的简体中文统一映射。"""


COUNTRY_TRANSLATIONS = {
    'Argentina': '阿根廷',
    'aus': '澳大利亚',
    'Australia': '澳大利亚',
    'Austria': '奥地利',
    'bel': '比利时',
    'Belgium': '比利时',
    'Bhutan': '不丹',
    'bra': '巴西',
    'Brazil': '巴西',
    'Bulgaria': '保加利亚',
    'can': '加拿大',
    'Canada': '加拿大',
    'che': '瑞士',
    'Chile': '智利',
    'China': '中国',
    'chn': '中国',
    'Colombia': '哥伦比亚',
    'Czech Republic': '捷克',
    '捷克共和国': '捷克',
    'Czechoslovakia': '捷克斯洛伐克',
    'Denmark': '丹麦',
    'deu': '德国',
    'dnk': '丹麦',
    'esp': '西班牙',
    'Finland': '芬兰',
    'fra': '法国',
    'France': '法国',
    'gbr': '英国',
    'geo': '格鲁吉亚',
    'Germany': '德国',
    'Greece': '希腊',
    'hkg': '中国香港',
    'Hong Kong': '中国香港',
    '中国香港特别行政区': '中国香港',
    '香港': '中国香港',
    'hun': '匈牙利',
    'Hungary': '匈牙利',
    'Iceland': '冰岛',
    'ind': '印度',
    'India': '印度',
    'Indonesia': '印度尼西亚',
    'Iran': '伊朗',
    'Ireland': '爱尔兰',
    'irl': '爱尔兰',
    'isl': '冰岛',
    'isr': '以色列',
    'Israel': '以色列',
    'ita': '意大利',
    'Italy': '意大利',
    'Japan': '日本',
    'jpn': '日本',
    'Kazakhstan': '哈萨克斯坦',
    'kor': '韩国',
    'South Korea': '韩国',
    'Latvia': '拉脱维亚',
    'lby': '利比亚',
    'lie': '列支敦士登',
    'Lithuania': '立陶宛',
    'Luxembourg': '卢森堡',
    'Macao': '中国澳门',
    '中国澳门特别行政区': '中国澳门',
    'Malaysia': '马来西亚',
    'Malta': '马耳他',
    'mex': '墨西哥',
    'Mexico': '墨西哥',
    'mng': '蒙古',
    'Netherlands': '荷兰',
    'New Zealand': '新西兰',
    'Nigeria': '尼日利亚',
    'nld': '荷兰',
    'nor': '挪威',
    'Norway': '挪威',
    'nzl': '新西兰',
    'Pakistan': '巴基斯坦',
    'Peru': '秘鲁',
    'Philippines': '菲律宾',
    'Poland': '波兰',
    'Portugal': '葡萄牙',
    'Romania': '罗马尼亚',
    'rus': '俄罗斯',
    'Russia': '俄罗斯',
    'Serbia': '塞尔维亚',
    'Serbia and Montenegro': '塞尔维亚和黑山',
    'Singapore': '新加坡',
    'Slovakia': '斯洛伐克',
    'Slovenia': '斯洛文尼亚',
    'South Africa': '南非',
    'Soviet Union': '苏联',
    'Spain': '西班牙',
    'swe': '瑞典',
    'Sweden': '瑞典',
    'Switzerland': '瑞士',
    'Taiwan': '中国台湾',
    'twn': '中国台湾',
    '台湾': '中国台湾',
    '台湾地区': '中国台湾',
    'Thailand': '泰国',
    'tur': '土耳其',
    'Turkey': '土耳其',
    'ukr': '乌克兰',
    'Ukraine': '乌克兰',
    'United Kingdom': '英国',
    'United States': '美国',
    'United States of America': '美国',
    'US': '美国',
    'usa': '美国',
    'Uruguay': '乌拉圭',
    'Venezuela': '委内瑞拉',
    'Vietnam': '越南',
    'West Germany': '西德',
    'Yugoslavia': '南斯拉夫',
    'zaf': '南非',
    '巴勒斯坦领土': '巴勒斯坦',
}
